blank_issues_enabled: false
contact_links:
  - name: Discord
    url: https://discord.h3.dev
    about: Join our Discord server to chat with the community and get help.
  - name: Github Discussions
    url: https://github.com/orgs/h3js/discussions
    about: Use discussions if you have another issue, an idea for improvement or for asking questions.
